name: 'The Grid: Games and Growlers'
favicon: null
layout_spectrum: 0.66329
typography_spectrum: 0.31848
title: "The Grid: America's first Synthwave Venue and Arizona's first Indie-Arcade"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0715'
    - '#4a3b74'
    - '#e3fefe'
    - '#8d80f2'
    - '#a9d8fe'
  brandStrength: 0.75
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
